export const START_LOADING = "START_LOADING";
export const GET_ALBUM_DATA = "GET_ALBUM_DATA";
export const SET_ALBUM_LINK_ERROR = "SET_ALBUM_LINK_ERROR";
export const UNSET_ALBUM_LINK_ERROR = "UNSET_ALBUM_LINK_ERROR";
export const TOGGLE_FAVORITE = "TOGGLE_FAVORITE";
export const ALBUM_LOADED = "ALBUM_LOADED";
export const ALREADY_FETCHED = "ALREADY_FETCHED";
export const ADD_PHOTO_COMMENT = "ADD_PHOTO_COMMENT";